# Generated by Django 4.0.2 on 2022-02-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
